export const ENABLE_ZONE_DEBUGGING = false;
export const SHOW_SOCIAL_LINKS = false;
export const TILE_SIZE = 64;
export const TILED_COLLISION_LAYER_ALPHA = 0;
export const TEXT_SPEED = Object.freeze({
  SLOW: 24,
  MEDIUM: 12,
  FAST: 4,
});
export const MOVEMENT_SPEED = Object.freeze({
  WALK_STEP_DURATION_MS: 220,
  RUN_STEP_DURATION_MS: 120,
  WALK_ANIMATION_TIME_SCALE: 2.4,
  RUN_ANIMATION_TIME_SCALE: 4,
});
export const BATTLE_TIMING = Object.freeze({
  ATTACK_WINDUP_MS: 160,
  ATTACK_SOUND_DELAY_MS: 35,
  QUICK_PAUSE_MS: 90,
  SEND_OUT_DELAY_MS: 320,
  SCENE_FADE_MS: 300,
  HEALTH_BAR_DURATION_MS: 300,
  DAMAGE_FLASH_DURATION_MS: 70,
  DAMAGE_FLASH_REPEAT: 5,
  MONSTER_APPEAR_DURATION_MS: 420,
  MONSTER_HEALTH_APPEAR_DURATION_MS: 360,
  PLAYER_APPEAR_DURATION_MS: 320,
  PLAYER_HEALTH_APPEAR_DURATION_MS: 320,
  FAINT_DURATION_MS: 620,
  NPC_APPEAR_DURATION_MS: 420,
  BALL_THROW_DURATION_MS: 450,
  BALL_SHAKE_DURATION_MS: 90,
  BALL_SHAKE_REPEAT_DELAY_MS: 170,
  BALL_SHAKE_DELAY_MS: 50,
  EXP_LEVEL_PAUSE_MS: 180,
});
export const MENU_COLOR = Object.freeze({
  1: {
    main: 0x32454c,
    border: 0x6d9aa8,
  },
  2: {
    main: 0x324c3a,
    border: 0x6da87d,
  },
  3: {
    main: 0x38324c,
    border: 0x796da8,
  },
});
